# Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=asdasd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# 'update' creará las tablas automáticamente en MySQL basándose en tus clases de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de JWT
# La clave secreta debe ser un texto largo y seguro en producción
app.jwt.secret=MiClaveSecretaSuperSeguraQueNadiePuedeAdivinarYEsMuyLarga123456
# Tiempo de validez del token en milisegundos (ej: 86400000 ms = 24 horas)
app.jwt.expiration-ms=86400000