# 1. Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# 2. Configuración de Hibernate (Crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Configuración del Token JWT (¡Los valores que usan tus compañeros!)
app.jwt.secret=MiClaveSecretaSuperSeguraQueNadiePuedeAdivinarYEsMuyLarga123456
app.jwt.expiration-ms=86400000

# 4. Puerto del microservicio
server.port=8091